/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    customers: Customer;
    invoices: Invoice;
    'customer-payments': CustomerPayment;
    categories: Category;
    warehouses: Warehouse;
    products: Product;
    'stock-movements': StockMovement;
    'bill-of-materials': BillOfMaterial;
    'production-orders': ProductionOrder;
    suppliers: Supplier;
    'purchase-invoices': PurchaseInvoice;
    'supplier-payments': SupplierPayment;
    'cash-registers': CashRegister;
    'cash-closures': CashClosure;
    'industry-templates': IndustryTemplate;
    quotes: Quote;
    orders: Order;
    'delivery-notes': DeliveryNote;
    alerts: Alert;
    'inventory-counts': InventoryCount;
    'price-history': PriceHistory;
    'audit-log': AuditLog;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      orders: 'orders';
    };
    orders: {
      deliveryNotes: 'delivery-notes';
    };
  };
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'customer-payments': CustomerPaymentsSelect<false> | CustomerPaymentsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    warehouses: WarehousesSelect<false> | WarehousesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    'bill-of-materials': BillOfMaterialsSelect<false> | BillOfMaterialsSelect<true>;
    'production-orders': ProductionOrdersSelect<false> | ProductionOrdersSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    'purchase-invoices': PurchaseInvoicesSelect<false> | PurchaseInvoicesSelect<true>;
    'supplier-payments': SupplierPaymentsSelect<false> | SupplierPaymentsSelect<true>;
    'cash-registers': CashRegistersSelect<false> | CashRegistersSelect<true>;
    'cash-closures': CashClosuresSelect<false> | CashClosuresSelect<true>;
    'industry-templates': IndustryTemplatesSelect<false> | IndustryTemplatesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'delivery-notes': DeliveryNotesSelect<false> | DeliveryNotesSelect<true>;
    alerts: AlertsSelect<false> | AlertsSelect<true>;
    'inventory-counts': InventoryCountsSelect<false> | InventoryCountsSelect<true>;
    'price-history': PriceHistorySelect<false> | PriceHistorySelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      seedIndustryTemplate: TaskSeedIndustryTemplate;
      evaluateAlerts: TaskEvaluateAlerts;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  rifFiscal?: string | null;
  phone?: string | null;
  currencyConfig?: {
    baseCurrency?: ('USD' | 'VES') | null;
    manualExchangeRate?: number | null;
    autoSyncRate?: boolean | null;
  };
  salesConfig: {
    /**
     * Escenario regulatorio venezolano 2026: en modo "nota_entrega" la entrega al cliente se documenta con Nota de Entrega y la factura pasa a ser opcional (se emite después, desde la remisión o el pedido).
     */
    salesDocumentDefault: 'nota_entrega' | 'factura';
  };
  taxConfig?: {
    /**
     * Rango legal 8–16,5%: ajustable por decreto del SENIAT sin cambios de código.
     */
    generalRatePct?: number | null;
    igtfPct?: number | null;
    applyIgtfOnFxPayments?: boolean | null;
  };
  emailConfig?: {
    /**
     * Requiere RESEND_API_KEY configurada. El cliente recibe un enlace público del presupuesto vía Resend; sin email del cliente no hay envío.
     */
    autoSendQuoteEmail?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'tenant-admin' | 'supervisor' | 'vendor' | 'cashier' | 'employee';
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  taxId: string;
  phone: string;
  email?: string | null;
  address?: string | null;
  /**
   * Define qué lista de precios del catálogo aplica por defecto a este cliente.
   */
  priceTier?: ('retail' | 'wholesale' | 'vendor' | 'promo') | null;
  /**
   * Representante comercial responsable de esta cuenta.
   */
  assignedVendor?: (number | null) | User;
  /**
   * Porcentaje sobre facturas pagadas de este cliente, derivado para el vendedor asignado.
   */
  commissionPct?: number | null;
  status: 'lead' | 'first_time' | 'recurring' | 'vip' | 'inactive';
  creditAllowed?: boolean | null;
  creditLimitUSD?: number | null;
  creditDays?: number | null;
  currentDebtUSD?: number | null;
  currentDebtVES?: number | null;
  overdueDebtUSD?: number | null;
  aging0to30?: number | null;
  aging31to60?: number | null;
  aging60Plus?: number | null;
  /**
   * Pedidos de venta asociados a este cliente.
   */
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  whatsappDebtUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Correlativo PED-##### generado por la Server Action (numeración con lock).
   */
  orderNumber: string;
  customer: number | Customer;
  /**
   * Segmento del cliente al momento de crear el pedido.
   */
  priceTierSnapshot?: ('retail' | 'wholesale' | 'vendor' | 'promo') | null;
  items: {
    /**
     * Opcional: las líneas sin producto son conceptos de texto libre.
     */
    product?: (number | null) | Product;
    sku?: string | null;
    description: string;
    quantity: number;
    unitPriceUSD: number;
    discountPct?: number | null;
    totalUSD?: number | null;
    id?: string | null;
  }[];
  issueDate?: string | null;
  confirmedAt?: string | null;
  status: 'draft' | 'confirmed' | 'invoiced' | 'canceled';
  exchangeRateSnapshot?: number | null;
  totalUSD?: number | null;
  totalVES?: number | null;
  /**
   * Se llena automáticamente al facturar el pedido confirmado.
   */
  issuedInvoice?: (number | null) | Invoice;
  notes?: string | null;
  /**
   * Remisiones de entrega emitidas desde este pedido.
   */
  deliveryNotes?: {
    docs?: (number | DeliveryNote)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  sku: string;
  barcode?: string | null;
  productType: 'standard' | 'raw_material' | 'manufactured' | 'service';
  category?: (number | null) | Category;
  unitOfMeasure: 'unit' | 'kg' | 'g' | 'l' | 'ml' | 'm' | 'box';
  costUSD: number;
  priceUSD: number;
  taxRate: 'exempt' | 'general' | 'reduced';
  trackInventory?: boolean | null;
  minStockAlert?: number | null;
  maxStock?: number | null;
  currentStock?: number | null;
  description?: string | null;
  image?: (number | null) | Media;
  isActive?: boolean | null;
  /**
   * El precio base (retail) es el campo "Precio Base de Venta". Agrega aquí los tiers alternativos; los documentos seleccionan el tier según el cliente.
   */
  priceTiers?:
    | {
        tier: 'wholesale' | 'vendor' | 'promo';
        priceUSD: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  code: string;
  description?: string | null;
  parentCategory?: (number | null) | Category;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  tenant?: (number | null) | Tenant;
  invoiceNumber: string;
  customer: number | Customer;
  /**
   * Usuario que emitió la factura. Base del cálculo de comisiones.
   */
  createdBy?: (number | null) | User;
  issueDate: string;
  dueDate: string;
  paymentTerms: 'cash' | 'credit';
  status: 'draft' | 'issued' | 'partially_paid' | 'paid' | 'voided';
  exchangeRateSnapshot: number;
  items: {
    sku?: string | null;
    description: string;
    quantity: number;
    unitPriceUSD: number;
    totalUSD?: number | null;
    /**
     * Vínculo al catálogo. Las líneas con producto descargan inventario al publicarse (Kardex); las de texto libre sin producto no afectan existencias.
     */
    product?: (number | null) | Product;
    id?: string | null;
  }[];
  totalUSD: number;
  totalVES: number;
  /**
   * Snapshot fiscal (Sprint 42): suma de líneas gravadas según el taxRate del producto. Informativo para el libro fiscal — no altera totalUSD.
   */
  taxBaseUSD?: number | null;
  /**
   * IVA del desglose (líneas × alícuota del catálogo, general configurable por inquilino). Informativo.
   */
  taxUSD?: number | null;
  balanceUSD: number;
  balanceVES: number;
  /**
   * Generado automáticamente al emitir a crédito. Los estados se reconcilian contra el balance pagado (hook transaccional); no editar manualmente.
   */
  installments?:
    | {
        number: number;
        dueDate: string;
        amountUSD: number;
        paidUSD?: number | null;
        status: 'pending' | 'partially_paid' | 'paid';
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  /**
   * De dónde sale el inventario de esta factura. Si se omite, se usa el almacén por defecto del inquilino. Solo se aplica al publicar la descarga (Kardex inmutable).
   */
  warehouse?: (number | null) | Warehouse;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses".
 */
export interface Warehouse {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  code: string;
  type: 'main' | 'raw_materials' | 'work_in_progress' | 'scrap' | 'retail';
  location?: string | null;
  isDefault?: boolean | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-notes".
 */
export interface DeliveryNote {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Correlativo REM-##### generado por la Server Action (numeración con lock).
   */
  noteNumber: string;
  order: number | Order;
  /**
   * Copia del cliente del pedido para trazabilidad de la remisión.
   */
  customer: number | Customer;
  items: {
    /**
     * Índice de la línea del pedido que este ítem despacha.
     */
    orderItemIndex: number;
    product?: (number | null) | Product;
    sku?: string | null;
    description: string;
    quantity: number;
    unitPriceUSD: number;
    discountPct?: number | null;
    id?: string | null;
  }[];
  issueDate?: string | null;
  status: 'issued' | 'voided';
  exchangeRateSnapshot?: number | null;
  totalUSD?: number | null;
  totalVES?: number | null;
  /**
   * Se llena si la mercancía despachada se facturó.
   */
  invoice?: (number | null) | Invoice;
  notes?: string | null;
  shareToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-payments".
 */
export interface CustomerPayment {
  id: number;
  tenant?: (number | null) | Tenant;
  paymentNumber: string;
  customer: number | Customer;
  paymentDate: string;
  status: 'pending' | 'confirmed' | 'rejected';
  methods: {
    method: 'cash_usd' | 'cash_ves' | 'pos_ves' | 'zelle' | 'pago_movil' | 'transfer_ves' | 'binance';
    currency: 'USD' | 'VES';
    amount: number;
    exchangeRate: number;
    amountUSD?: number | null;
    reference?: string | null;
    receipt?: (number | null) | Media;
    id?: string | null;
  }[];
  /**
   * Snapshot informativo (Sprint 42): IGTF del cobro si el método es divisa (config por inquilino en taxConfig).
   */
  igtfUSD?: number | null;
  totalUSD: number;
  allocations?:
    | {
        invoice: number | Invoice;
        allocatedAmountUSD: number;
        id?: string | null;
      }[]
    | null;
  cashRegister?: (number | null) | CashRegister;
  cashClosure?: (number | null) | CashClosure;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-registers".
 */
export interface CashRegister {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  code: string;
  warehouse: number | Warehouse;
  assignedUsers?: (number | User)[] | null;
  currentStatus: 'open' | 'closed';
  currentClosure?: (number | null) | CashClosure;
  active?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-closures".
 */
export interface CashClosure {
  id: number;
  tenant?: (number | null) | Tenant;
  closureNumber: string;
  cashRegister: number | CashRegister;
  openedBy: number | User;
  closedBy?: (number | null) | User;
  auditedBy?: (number | null) | User;
  status: 'open' | 'closed' | 'audited';
  openedAt: string;
  closedAt?: string | null;
  auditedAt?: string | null;
  openingFloat?: {
    cashUSD?: number | null;
    cashVES?: number | null;
    notes?: string | null;
  };
  declaredTotals?: {
    cashUSD?: number | null;
    cashVES?: number | null;
    posVES?: number | null;
    pagoMovilVES?: number | null;
    transferVES?: number | null;
    zelleUSD?: number | null;
    binanceUSD?: number | null;
  };
  systemTotals?: {
    collections?: {
      cashUSD?: number | null;
      cashVES?: number | null;
      posVES?: number | null;
      pagoMovilVES?: number | null;
      transferVES?: number | null;
      zelleUSD?: number | null;
      binanceUSD?: number | null;
      totalCollectionsUSD?: number | null;
    };
    disbursements?: {
      cashUSDOut?: number | null;
      cashVESOut?: number | null;
      posVESOut?: number | null;
      pagoMovilVESOut?: number | null;
      transferVESOut?: number | null;
      zelleUSDOut?: number | null;
      binanceUSDOut?: number | null;
      totalDisbursementsUSD?: number | null;
    };
    expected?: {
      expectedCashUSD?: number | null;
      expectedCashVES?: number | null;
      expectedPosVES?: number | null;
      expectedPagoMovilVES?: number | null;
      expectedTransferVES?: number | null;
      expectedZelleUSD?: number | null;
      expectedBinanceUSD?: number | null;
      netTotalUSD?: number | null;
    };
  };
  differences?: {
    diffCashUSD?: number | null;
    diffCashVES?: number | null;
    diffPosVES?: number | null;
    diffPagoMovilVES?: number | null;
    diffTransferVES?: number | null;
    diffZelleUSD?: number | null;
    diffBinanceUSD?: number | null;
    totalDiscrepancyUSD?: number | null;
    hasDiscrepancy?: boolean | null;
  };
  notes?: string | null;
  supervisorNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: number;
  tenant?: (number | null) | Tenant;
  reference: string;
  movementType:
    | 'purchase_in'
    | 'sale_out'
    | 'production_consume'
    | 'production_output'
    | 'transfer'
    | 'adjustment_positive'
    | 'adjustment_negative'
    | 'scrap'
    | 'sale_return';
  product: number | Product;
  sourceWarehouse?: (number | null) | Warehouse;
  targetWarehouse?: (number | null) | Warehouse;
  quantity: number;
  unitCostUSD: number;
  totalCostUSD: number;
  reason?: string | null;
  productionOrder?: (number | null) | ProductionOrder;
  invoice?: (number | null) | Invoice;
  purchaseInvoice?: (number | null) | PurchaseInvoice;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-orders".
 */
export interface ProductionOrder {
  id: number;
  tenant?: (number | null) | Tenant;
  orderNumber: string;
  product: number | Product;
  bom: number | BillOfMaterial;
  quantityPlanned: number;
  quantityProduced?: number | null;
  sourceWarehouse: number | Warehouse;
  targetWarehouse: number | Warehouse;
  status: 'draft' | 'planned' | 'in_progress' | 'completed' | 'cancelled';
  startDate?: string | null;
  completionDate?: string | null;
  totalCostUSD?: number | null;
  unitCostUSD?: number | null;
  assignedTo?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bill-of-materials".
 */
export interface BillOfMaterial {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  product: number | Product;
  outputQuantity: number;
  items: {
    rawMaterial: number | Product;
    quantity: number;
    scrapFactorPercent?: number | null;
    unitCostSnapshotUSD?: number | null;
    subtotalCostUSD?: number | null;
    id?: string | null;
  }[];
  laborCostUSD?: number | null;
  indirectCostsUSD?: number | null;
  totalBatchCostUSD?: number | null;
  totalUnitCostUSD?: number | null;
  instructions?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-invoices".
 */
export interface PurchaseInvoice {
  id: number;
  tenant?: (number | null) | Tenant;
  invoiceNumber: string;
  supplier: number | Supplier;
  issueDate: string;
  dueDate: string;
  paymentTerms: 'cash' | 'credit';
  status: 'draft' | 'received' | 'partially_paid' | 'paid' | 'voided';
  receptionStatus: 'pending' | 'received';
  /**
   * Obligatorio si la compra incluye productos físicos que ingresarán a inventario.
   */
  receptionWarehouse?: (number | null) | Warehouse;
  receptionDate?: string | null;
  exchangeRateSnapshot: number;
  items: {
    product?: (number | null) | Product;
    sku?: string | null;
    description: string;
    quantity: number;
    unitCostUSD: number;
    totalUSD?: number | null;
    id?: string | null;
  }[];
  totalUSD: number;
  totalVES: number;
  balanceUSD: number;
  balanceVES: number;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  taxId: string;
  contactName?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  creditAllowed?: boolean | null;
  creditLimitUSD?: number | null;
  creditDays?: number | null;
  currentDebtUSD?: number | null;
  currentDebtVES?: number | null;
  overdueDebtUSD?: number | null;
  aging0to30?: number | null;
  aging31to60?: number | null;
  aging60Plus?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-payments".
 */
export interface SupplierPayment {
  id: number;
  tenant?: (number | null) | Tenant;
  paymentNumber: string;
  supplier: number | Supplier;
  paymentDate: string;
  status: 'pending' | 'confirmed' | 'rejected';
  methods: {
    method: 'cash_usd' | 'cash_ves' | 'pos_ves' | 'zelle' | 'pago_movil' | 'transfer_ves' | 'binance';
    currency: 'USD' | 'VES';
    amount: number;
    exchangeRate: number;
    amountUSD?: number | null;
    reference?: string | null;
    receipt?: (number | null) | Media;
    id?: string | null;
  }[];
  totalUSD: number;
  allocations?:
    | {
        purchaseInvoice: number | PurchaseInvoice;
        allocatedAmountUSD: number;
        id?: string | null;
      }[]
    | null;
  cashRegister?: (number | null) | CashRegister;
  cashClosure?: (number | null) | CashClosure;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-templates".
 */
export interface IndustryTemplate {
  id: number;
  name: string;
  slug: string;
  description: string;
  industryType: 'food_production' | 'retail_health' | 'wholesale' | 'services';
  icon?: string | null;
  isPublished?: boolean | null;
  defaultPaymentMethods?:
    ('cash_usd' | 'cash_ves' | 'pos_ves' | 'pago_movil' | 'transfer_ves' | 'zelle' | 'binance')[] | null;
  templateData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Correlativo COT-##### generado por la Server Action (numeración con lock).
   */
  quoteNumber: string;
  customer: number | Customer;
  items: {
    /**
     * Opcional: las líneas sin producto son conceptos de texto libre.
     */
    product?: (number | null) | Product;
    sku?: string | null;
    description: string;
    quantity: number;
    unitPriceUSD: number;
    totalUSD?: number | null;
    id?: string | null;
  }[];
  issueDate?: string | null;
  validUntil?: string | null;
  status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'converted';
  exchangeRateSnapshot?: number | null;
  totalUSD?: number | null;
  totalVES?: number | null;
  /**
   * Se llena automáticamente al convertir la cotización en factura.
   */
  convertedInvoice?: (number | null) | Invoice;
  notes?: string | null;
  shareToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts".
 */
export interface Alert {
  id: number;
  tenant?: (number | null) | Tenant;
  type: 'low_stock' | 'inventory_diff' | 'rate_change' | 'overdue_invoice' | 'vendor_overdue';
  severity: 'info' | 'warning' | 'critical';
  message: string;
  /**
   * Slug de la colección referida (products, invoices, inventory-counts…).
   */
  refCollection?: string | null;
  /**
   * ID del documento referido; 0 para alertas a nivel de inquilino.
   */
  refId: number;
  acknowledgedAt?: string | null;
  acknowledgedBy?: (number | null) | User;
  /**
   * Vacía = alerta activa. El evaluador reactiva la fila si la condición reaparece.
   */
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Conteo físico por almacén con snapshot del sistema y ajustes por Kardex al completar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-counts".
 */
export interface InventoryCount {
  id: number;
  tenant?: (number | null) | Tenant;
  warehouse: number | Warehouse;
  status: 'in_progress' | 'completed';
  items: {
    product: number | Product;
    systemQty: number;
    countedQty?: number | null;
    difference?: number | null;
    id?: string | null;
  }[];
  notes?: string | null;
  openedBy?: (number | null) | User;
  completedBy?: (number | null) | User;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bitácora inmutable de cambios de precio (escrita por el pricingPlugin).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-history".
 */
export interface PriceHistory {
  id: number;
  tenant?: (number | null) | Tenant;
  product: number | Product;
  oldPriceUSD: number;
  newPriceUSD: number;
  exchangeRateSnapshot: number;
  newPriceVES: number;
  trigger: 'manual' | 'rate_change';
  changedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bitácora inmutable escrita por auditPlugin: quién cambió qué, cuándo y con qué diff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  /**
   * Inquilino del documento auditado (vacío en operaciones globales).
   */
  tenant?: (number | null) | Tenant;
  /**
   * Usuario que realizó la operación (sistema si no aplica).
   */
  actor?: (number | null) | User;
  actorRole?: string | null;
  collection: string;
  docId: number;
  operation: 'create' | 'update' | 'delete';
  /**
   * Solo en updates: campos cuyo valor cambió.
   */
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Estado final del documento (create) o previo (delete).
   */
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          'inline' | 'seedIndustryTemplate' | 'evaluateAlerts' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    ('inline' | 'seedIndustryTemplate' | 'evaluateAlerts' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'customer-payments';
        value: number | CustomerPayment;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'warehouses';
        value: number | Warehouse;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'bill-of-materials';
        value: number | BillOfMaterial;
      } | null)
    | ({
        relationTo: 'production-orders';
        value: number | ProductionOrder;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'purchase-invoices';
        value: number | PurchaseInvoice;
      } | null)
    | ({
        relationTo: 'supplier-payments';
        value: number | SupplierPayment;
      } | null)
    | ({
        relationTo: 'cash-registers';
        value: number | CashRegister;
      } | null)
    | ({
        relationTo: 'cash-closures';
        value: number | CashClosure;
      } | null)
    | ({
        relationTo: 'industry-templates';
        value: number | IndustryTemplate;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'delivery-notes';
        value: number | DeliveryNote;
      } | null)
    | ({
        relationTo: 'alerts';
        value: number | Alert;
      } | null)
    | ({
        relationTo: 'inventory-counts';
        value: number | InventoryCount;
      } | null)
    | ({
        relationTo: 'price-history';
        value: number | PriceHistory;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  rifFiscal?: T;
  phone?: T;
  currencyConfig?:
    | T
    | {
        baseCurrency?: T;
        manualExchangeRate?: T;
        autoSyncRate?: T;
      };
  salesConfig?:
    | T
    | {
        salesDocumentDefault?: T;
      };
  taxConfig?:
    | T
    | {
        generalRatePct?: T;
        igtfPct?: T;
        applyIgtfOnFxPayments?: T;
      };
  emailConfig?:
    | T
    | {
        autoSendQuoteEmail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  taxId?: T;
  phone?: T;
  email?: T;
  address?: T;
  priceTier?: T;
  assignedVendor?: T;
  commissionPct?: T;
  status?: T;
  creditAllowed?: T;
  creditLimitUSD?: T;
  creditDays?: T;
  currentDebtUSD?: T;
  currentDebtVES?: T;
  overdueDebtUSD?: T;
  aging0to30?: T;
  aging31to60?: T;
  aging60Plus?: T;
  orders?: T;
  whatsappDebtUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  tenant?: T;
  invoiceNumber?: T;
  customer?: T;
  createdBy?: T;
  issueDate?: T;
  dueDate?: T;
  paymentTerms?: T;
  status?: T;
  exchangeRateSnapshot?: T;
  items?:
    | T
    | {
        sku?: T;
        description?: T;
        quantity?: T;
        unitPriceUSD?: T;
        totalUSD?: T;
        product?: T;
        id?: T;
      };
  totalUSD?: T;
  totalVES?: T;
  taxBaseUSD?: T;
  taxUSD?: T;
  balanceUSD?: T;
  balanceVES?: T;
  installments?:
    | T
    | {
        number?: T;
        dueDate?: T;
        amountUSD?: T;
        paidUSD?: T;
        status?: T;
        id?: T;
      };
  notes?: T;
  warehouse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-payments_select".
 */
export interface CustomerPaymentsSelect<T extends boolean = true> {
  tenant?: T;
  paymentNumber?: T;
  customer?: T;
  paymentDate?: T;
  status?: T;
  methods?:
    | T
    | {
        method?: T;
        currency?: T;
        amount?: T;
        exchangeRate?: T;
        amountUSD?: T;
        reference?: T;
        receipt?: T;
        id?: T;
      };
  igtfUSD?: T;
  totalUSD?: T;
  allocations?:
    | T
    | {
        invoice?: T;
        allocatedAmountUSD?: T;
        id?: T;
      };
  cashRegister?: T;
  cashClosure?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  code?: T;
  description?: T;
  parentCategory?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses_select".
 */
export interface WarehousesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  code?: T;
  type?: T;
  location?: T;
  isDefault?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  sku?: T;
  barcode?: T;
  productType?: T;
  category?: T;
  unitOfMeasure?: T;
  costUSD?: T;
  priceUSD?: T;
  taxRate?: T;
  trackInventory?: T;
  minStockAlert?: T;
  maxStock?: T;
  currentStock?: T;
  description?: T;
  image?: T;
  isActive?: T;
  priceTiers?:
    | T
    | {
        tier?: T;
        priceUSD?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  tenant?: T;
  reference?: T;
  movementType?: T;
  product?: T;
  sourceWarehouse?: T;
  targetWarehouse?: T;
  quantity?: T;
  unitCostUSD?: T;
  totalCostUSD?: T;
  reason?: T;
  productionOrder?: T;
  invoice?: T;
  purchaseInvoice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bill-of-materials_select".
 */
export interface BillOfMaterialsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  product?: T;
  outputQuantity?: T;
  items?:
    | T
    | {
        rawMaterial?: T;
        quantity?: T;
        scrapFactorPercent?: T;
        unitCostSnapshotUSD?: T;
        subtotalCostUSD?: T;
        id?: T;
      };
  laborCostUSD?: T;
  indirectCostsUSD?: T;
  totalBatchCostUSD?: T;
  totalUnitCostUSD?: T;
  instructions?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-orders_select".
 */
export interface ProductionOrdersSelect<T extends boolean = true> {
  tenant?: T;
  orderNumber?: T;
  product?: T;
  bom?: T;
  quantityPlanned?: T;
  quantityProduced?: T;
  sourceWarehouse?: T;
  targetWarehouse?: T;
  status?: T;
  startDate?: T;
  completionDate?: T;
  totalCostUSD?: T;
  unitCostUSD?: T;
  assignedTo?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  taxId?: T;
  contactName?: T;
  phone?: T;
  email?: T;
  address?: T;
  creditAllowed?: T;
  creditLimitUSD?: T;
  creditDays?: T;
  currentDebtUSD?: T;
  currentDebtVES?: T;
  overdueDebtUSD?: T;
  aging0to30?: T;
  aging31to60?: T;
  aging60Plus?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-invoices_select".
 */
export interface PurchaseInvoicesSelect<T extends boolean = true> {
  tenant?: T;
  invoiceNumber?: T;
  supplier?: T;
  issueDate?: T;
  dueDate?: T;
  paymentTerms?: T;
  status?: T;
  receptionStatus?: T;
  receptionWarehouse?: T;
  receptionDate?: T;
  exchangeRateSnapshot?: T;
  items?:
    | T
    | {
        product?: T;
        sku?: T;
        description?: T;
        quantity?: T;
        unitCostUSD?: T;
        totalUSD?: T;
        id?: T;
      };
  totalUSD?: T;
  totalVES?: T;
  balanceUSD?: T;
  balanceVES?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-payments_select".
 */
export interface SupplierPaymentsSelect<T extends boolean = true> {
  tenant?: T;
  paymentNumber?: T;
  supplier?: T;
  paymentDate?: T;
  status?: T;
  methods?:
    | T
    | {
        method?: T;
        currency?: T;
        amount?: T;
        exchangeRate?: T;
        amountUSD?: T;
        reference?: T;
        receipt?: T;
        id?: T;
      };
  totalUSD?: T;
  allocations?:
    | T
    | {
        purchaseInvoice?: T;
        allocatedAmountUSD?: T;
        id?: T;
      };
  cashRegister?: T;
  cashClosure?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-registers_select".
 */
export interface CashRegistersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  code?: T;
  warehouse?: T;
  assignedUsers?: T;
  currentStatus?: T;
  currentClosure?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-closures_select".
 */
export interface CashClosuresSelect<T extends boolean = true> {
  tenant?: T;
  closureNumber?: T;
  cashRegister?: T;
  openedBy?: T;
  closedBy?: T;
  auditedBy?: T;
  status?: T;
  openedAt?: T;
  closedAt?: T;
  auditedAt?: T;
  openingFloat?:
    | T
    | {
        cashUSD?: T;
        cashVES?: T;
        notes?: T;
      };
  declaredTotals?:
    | T
    | {
        cashUSD?: T;
        cashVES?: T;
        posVES?: T;
        pagoMovilVES?: T;
        transferVES?: T;
        zelleUSD?: T;
        binanceUSD?: T;
      };
  systemTotals?:
    | T
    | {
        collections?:
          | T
          | {
              cashUSD?: T;
              cashVES?: T;
              posVES?: T;
              pagoMovilVES?: T;
              transferVES?: T;
              zelleUSD?: T;
              binanceUSD?: T;
              totalCollectionsUSD?: T;
            };
        disbursements?:
          | T
          | {
              cashUSDOut?: T;
              cashVESOut?: T;
              posVESOut?: T;
              pagoMovilVESOut?: T;
              transferVESOut?: T;
              zelleUSDOut?: T;
              binanceUSDOut?: T;
              totalDisbursementsUSD?: T;
            };
        expected?:
          | T
          | {
              expectedCashUSD?: T;
              expectedCashVES?: T;
              expectedPosVES?: T;
              expectedPagoMovilVES?: T;
              expectedTransferVES?: T;
              expectedZelleUSD?: T;
              expectedBinanceUSD?: T;
              netTotalUSD?: T;
            };
      };
  differences?:
    | T
    | {
        diffCashUSD?: T;
        diffCashVES?: T;
        diffPosVES?: T;
        diffPagoMovilVES?: T;
        diffTransferVES?: T;
        diffZelleUSD?: T;
        diffBinanceUSD?: T;
        totalDiscrepancyUSD?: T;
        hasDiscrepancy?: T;
      };
  notes?: T;
  supervisorNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-templates_select".
 */
export interface IndustryTemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  industryType?: T;
  icon?: T;
  isPublished?: T;
  defaultPaymentMethods?: T;
  templateData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  tenant?: T;
  quoteNumber?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        sku?: T;
        description?: T;
        quantity?: T;
        unitPriceUSD?: T;
        totalUSD?: T;
        id?: T;
      };
  issueDate?: T;
  validUntil?: T;
  status?: T;
  exchangeRateSnapshot?: T;
  totalUSD?: T;
  totalVES?: T;
  convertedInvoice?: T;
  notes?: T;
  shareToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  tenant?: T;
  orderNumber?: T;
  customer?: T;
  priceTierSnapshot?: T;
  items?:
    | T
    | {
        product?: T;
        sku?: T;
        description?: T;
        quantity?: T;
        unitPriceUSD?: T;
        discountPct?: T;
        totalUSD?: T;
        id?: T;
      };
  issueDate?: T;
  confirmedAt?: T;
  status?: T;
  exchangeRateSnapshot?: T;
  totalUSD?: T;
  totalVES?: T;
  issuedInvoice?: T;
  notes?: T;
  deliveryNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-notes_select".
 */
export interface DeliveryNotesSelect<T extends boolean = true> {
  tenant?: T;
  noteNumber?: T;
  order?: T;
  customer?: T;
  items?:
    | T
    | {
        orderItemIndex?: T;
        product?: T;
        sku?: T;
        description?: T;
        quantity?: T;
        unitPriceUSD?: T;
        discountPct?: T;
        id?: T;
      };
  issueDate?: T;
  status?: T;
  exchangeRateSnapshot?: T;
  totalUSD?: T;
  totalVES?: T;
  invoice?: T;
  notes?: T;
  shareToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts_select".
 */
export interface AlertsSelect<T extends boolean = true> {
  tenant?: T;
  type?: T;
  severity?: T;
  message?: T;
  refCollection?: T;
  refId?: T;
  acknowledgedAt?: T;
  acknowledgedBy?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-counts_select".
 */
export interface InventoryCountsSelect<T extends boolean = true> {
  tenant?: T;
  warehouse?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        systemQty?: T;
        countedQty?: T;
        difference?: T;
        id?: T;
      };
  notes?: T;
  openedBy?: T;
  completedBy?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-history_select".
 */
export interface PriceHistorySelect<T extends boolean = true> {
  tenant?: T;
  product?: T;
  oldPriceUSD?: T;
  newPriceUSD?: T;
  exchangeRateSnapshot?: T;
  newPriceVES?: T;
  trigger?: T;
  changedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  tenant?: T;
  actor?: T;
  actorRole?: T;
  collection?: T;
  docId?: T;
  operation?: T;
  diff?: T;
  snapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSeedIndustryTemplate".
 */
export interface TaskSeedIndustryTemplate {
  input: {
    tenantId: number;
    templateSlug: string;
    userId: number;
  };
  output: {
    success: boolean;
    message: string;
    templateName: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskEvaluateAlerts".
 */
export interface TaskEvaluateAlerts {
  input?: unknown;
  output: {
    tenants: number;
    created: number;
    updated: number;
    resolved: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'tenants'
      | 'users'
      | 'media'
      | 'customers'
      | 'invoices'
      | 'customer-payments'
      | 'categories'
      | 'warehouses'
      | 'products'
      | 'stock-movements'
      | 'bill-of-materials'
      | 'production-orders'
      | 'suppliers'
      | 'purchase-invoices'
      | 'supplier-payments'
      | 'cash-registers'
      | 'cash-closures'
      | 'industry-templates'
      | 'quotes'
      | 'orders'
      | 'delivery-notes'
      | 'alerts'
      | 'inventory-counts'
      | 'price-history'
      | 'audit-log'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}