/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    customers: Customer;
    invoices: Invoice;
    'customer-payments': CustomerPayment;
    categories: Category;
    warehouses: Warehouse;
    products: Product;
    'stock-movements': StockMovement;
    'bill-of-materials': BillOfMaterial;
    'production-orders': ProductionOrder;
    suppliers: Supplier;
    'purchase-invoices': PurchaseInvoice;
    'supplier-payments': SupplierPayment;
    'cash-registers': CashRegister;
    'cash-closures': CashClosure;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'customer-payments': CustomerPaymentsSelect<false> | CustomerPaymentsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    warehouses: WarehousesSelect<false> | WarehousesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    'bill-of-materials': BillOfMaterialsSelect<false> | BillOfMaterialsSelect<true>;
    'production-orders': ProductionOrdersSelect<false> | ProductionOrdersSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    'purchase-invoices': PurchaseInvoicesSelect<false> | PurchaseInvoicesSelect<true>;
    'supplier-payments': SupplierPaymentsSelect<false> | SupplierPaymentsSelect<true>;
    'cash-registers': CashRegistersSelect<false> | CashRegistersSelect<true>;
    'cash-closures': CashClosuresSelect<false> | CashClosuresSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  rifFiscal?: string | null;
  phone?: string | null;
  currencyConfig?: {
    baseCurrency?: ('USD' | 'VES') | null;
    manualExchangeRate?: number | null;
    autoSyncRate?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'tenant-admin' | 'supervisor' | 'cashier' | 'employee';
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  legalName?: string | null;
  rifCi: string;
  phone: string;
  email?: string | null;
  address?: string | null;
  lifecycleStage?: ('lead' | 'first_time' | 'recurring' | 'vip' | 'inactive') | null;
  creditConfig?: {
    creditAllowed?: boolean | null;
    creditLimitUSD?: number | null;
    creditDays?: number | null;
  };
  currentDebtUSD?: number | null;
  currentDebtVES?: number | null;
  overdueDebtUSD?: number | null;
  lastPaymentDate?: string | null;
  whatsappChatUrl?: string | null;
  creditStatus?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  tenant?: (number | null) | Tenant;
  invoiceNumber: string;
  customer: number | Customer;
  paymentType?: ('credit' | 'cash') | null;
  status?: ('draft' | 'pending' | 'partially_paid' | 'paid' | 'cancelled') | null;
  issueDate: string;
  dueDate?: string | null;
  exchangeRateSnapshot: number;
  totalUSD: number;
  totalVES?: number | null;
  balanceUSD?: number | null;
  balanceVES?: number | null;
  items?:
    | {
        sku?: string | null;
        description: string;
        quantity: number;
        unitPriceUSD: number;
        subtotalUSD?: number | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-payments".
 */
export interface CustomerPayment {
  id: number;
  tenant?: (number | null) | Tenant;
  paymentNumber: string;
  customer: number | Customer;
  paymentDate: string;
  paymentMethod: 'pago_movil' | 'transfer_ves' | 'cash_usd' | 'cash_ves' | 'zelle' | 'binance';
  amountUSD: number;
  exchangeRateApplied: number;
  amountVES?: number | null;
  reference?: string | null;
  allocations?:
    | {
        invoice: number | Invoice;
        allocatedAmountUSD: number;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  parentCategory?: (number | null) | Category;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses".
 */
export interface Warehouse {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  code: string;
  type?: ('general' | 'raw_materials' | 'production_floor' | 'transit') | null;
  isDefault?: boolean | null;
  active?: boolean | null;
  address?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  sku: string;
  barcode?: string | null;
  productType: 'standard' | 'raw_material' | 'manufactured' | 'combo';
  category?: (number | null) | Category;
  unitOfMeasure: 'unit' | 'kg' | 'g' | 'l' | 'ml' | 'm' | 'box' | 'pack';
  pricing: {
    salePriceUSD: number;
    wholesalePriceUSD?: number | null;
    costPriceUSD?: number | null;
    /**
     * Recalculado automáticamente por compras y órdenes de fabricación.
     */
    averageCostUSD?: number | null;
  };
  inventory?: {
    /**
     * Gobernado por los movimientos inmutables de Kardex.
     */
    stockQuantity?: number | null;
    minStock?: number | null;
    reorderPoint?: number | null;
  };
  active?: boolean | null;
  images?: (number | Media)[] | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: number;
  tenant?: (number | null) | Tenant;
  reference: string;
  product: number | Product;
  warehouse: number | Warehouse;
  movementType:
    | 'purchase'
    | 'sale'
    | 'transfer'
    | 'adjustment_in'
    | 'adjustment_out'
    | 'raw_material_consumption'
    | 'production_receipt'
    | 'initial_stock';
  quantity: number;
  unitCostUSD: number;
  totalValueUSD?: number | null;
  movementDate: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bill-of-materials".
 */
export interface BillOfMaterial {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  code: string;
  finishedProduct: number | Product;
  yieldQuantity: number;
  yieldUnit: 'unit' | 'kg' | 'g' | 'l' | 'box' | 'pack';
  version?: string | null;
  status?: ('active' | 'draft' | 'archived') | null;
  components: {
    rawMaterial: number | Product;
    quantity: number;
    unit: string;
    scrapPercentage?: number | null;
    unitCostSnapshot?: number | null;
    subtotalCostUSD?: number | null;
    id?: string | null;
  }[];
  costs?: {
    laborCostUSD?: number | null;
    overheadCostUSD?: number | null;
    totalRawMaterialCostUSD?: number | null;
    totalBatchCostUSD?: number | null;
    /**
     * Costo unitario teórico (Costo Lote / Rendimiento Base).
     */
    unitProductionCostUSD?: number | null;
  };
  instructions?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-orders".
 */
export interface ProductionOrder {
  id: number;
  tenant?: (number | null) | Tenant;
  orderNumber: string;
  bom: number | BillOfMaterial;
  finishedProduct: number | Product;
  sourceWarehouse: number | Warehouse;
  targetWarehouse: number | Warehouse;
  plannedQuantity: number;
  /**
   * Cantidad física efectivamente terminada en la corrida de producción.
   */
  producedQuantity?: number | null;
  status?: ('draft' | 'planned' | 'in_progress' | 'completed' | 'cancelled') | null;
  scheduledDate?: string | null;
  completedDate?: string | null;
  actualCosts?: {
    actualTotalCostUSD?: number | null;
    actualUnitCostUSD?: number | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  legalName?: string | null;
  rifTaxId: string;
  phone: string;
  email?: string | null;
  contactPerson?: string | null;
  creditConfig?: {
    creditAllowed?: boolean | null;
    creditDays?: number | null;
    creditLimitUSD?: number | null;
  };
  currentDebtUSD?: number | null;
  currentDebtVES?: number | null;
  overdueDebtUSD?: number | null;
  lastPaymentDate?: string | null;
  /**
   * Cuentas bancarias, beneficiario, RIF, correo para confirmaciones de pago.
   */
  paymentInstructions?: string | null;
  address?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-invoices".
 */
export interface PurchaseInvoice {
  id: number;
  tenant?: (number | null) | Tenant;
  invoiceReference: string;
  supplier: number | Supplier;
  /**
   * Almacén donde ingresa físicamente la mercancía o materia prima comprada.
   */
  warehouse?: (number | null) | Warehouse;
  paymentType?: ('credit' | 'cash') | null;
  status?: ('pending' | 'partially_paid' | 'paid' | 'cancelled') | null;
  issueDate: string;
  dueDate?: string | null;
  exchangeRateSnapshot: number;
  totalUSD: number;
  totalVES?: number | null;
  balanceUSD?: number | null;
  balanceVES?: number | null;
  items?:
    | {
        product?: (number | null) | Product;
        sku?: string | null;
        description: string;
        quantity: number;
        unitCostUSD: number;
        subtotalUSD?: number | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-payments".
 */
export interface SupplierPayment {
  id: number;
  tenant?: (number | null) | Tenant;
  paymentNumber: string;
  supplier: number | Supplier;
  paymentDate: string;
  paymentMethod: 'transfer_ves' | 'pago_movil' | 'cash_usd' | 'cash_ves' | 'zelle' | 'binance';
  amountUSD: number;
  exchangeRateApplied: number;
  amountVES?: number | null;
  bankOrigin?: string | null;
  reference?: string | null;
  allocations?:
    | {
        purchaseInvoice: number | PurchaseInvoice;
        allocatedAmountUSD: number;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-registers".
 */
export interface CashRegister {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  code: string;
  warehouse: number | Warehouse;
  currentStatus?: ('open' | 'closed') | null;
  active?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-closures".
 */
export interface CashClosure {
  id: number;
  tenant?: (number | null) | Tenant;
  closureNumber: string;
  cashRegister: number | CashRegister;
  openedBy: number | User;
  closedBy?: (number | null) | User;
  status?: ('open' | 'closed' | 'audited') | null;
  openedAt: string;
  closedAt?: string | null;
  openingFloat?: {
    cashUSD?: number | null;
    cashVES?: number | null;
  };
  systemTotals?: {
    cashUSD?: number | null;
    cashVES?: number | null;
    pagoMovilVES?: number | null;
    transferVES?: number | null;
    zelleUSD?: number | null;
    binanceUSD?: number | null;
    totalSalesUSD?: number | null;
  };
  declaredTotals?: {
    cashUSD?: number | null;
    cashVES?: number | null;
    pagoMovilVES?: number | null;
    transferVES?: number | null;
    zelleUSD?: number | null;
    binanceUSD?: number | null;
  };
  differences?: {
    diffCashUSD?: number | null;
    diffCashVES?: number | null;
    diffPagoMovilVES?: number | null;
    diffZelleUSD?: number | null;
    hasDiscrepancy?: boolean | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'customer-payments';
        value: number | CustomerPayment;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'warehouses';
        value: number | Warehouse;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'bill-of-materials';
        value: number | BillOfMaterial;
      } | null)
    | ({
        relationTo: 'production-orders';
        value: number | ProductionOrder;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'purchase-invoices';
        value: number | PurchaseInvoice;
      } | null)
    | ({
        relationTo: 'supplier-payments';
        value: number | SupplierPayment;
      } | null)
    | ({
        relationTo: 'cash-registers';
        value: number | CashRegister;
      } | null)
    | ({
        relationTo: 'cash-closures';
        value: number | CashClosure;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  rifFiscal?: T;
  phone?: T;
  currencyConfig?:
    | T
    | {
        baseCurrency?: T;
        manualExchangeRate?: T;
        autoSyncRate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  legalName?: T;
  rifCi?: T;
  phone?: T;
  email?: T;
  address?: T;
  lifecycleStage?: T;
  creditConfig?:
    | T
    | {
        creditAllowed?: T;
        creditLimitUSD?: T;
        creditDays?: T;
      };
  currentDebtUSD?: T;
  currentDebtVES?: T;
  overdueDebtUSD?: T;
  lastPaymentDate?: T;
  whatsappChatUrl?: T;
  creditStatus?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  tenant?: T;
  invoiceNumber?: T;
  customer?: T;
  paymentType?: T;
  status?: T;
  issueDate?: T;
  dueDate?: T;
  exchangeRateSnapshot?: T;
  totalUSD?: T;
  totalVES?: T;
  balanceUSD?: T;
  balanceVES?: T;
  items?:
    | T
    | {
        sku?: T;
        description?: T;
        quantity?: T;
        unitPriceUSD?: T;
        subtotalUSD?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-payments_select".
 */
export interface CustomerPaymentsSelect<T extends boolean = true> {
  tenant?: T;
  paymentNumber?: T;
  customer?: T;
  paymentDate?: T;
  paymentMethod?: T;
  amountUSD?: T;
  exchangeRateApplied?: T;
  amountVES?: T;
  reference?: T;
  allocations?:
    | T
    | {
        invoice?: T;
        allocatedAmountUSD?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  parentCategory?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses_select".
 */
export interface WarehousesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  code?: T;
  type?: T;
  isDefault?: T;
  active?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  sku?: T;
  barcode?: T;
  productType?: T;
  category?: T;
  unitOfMeasure?: T;
  pricing?:
    | T
    | {
        salePriceUSD?: T;
        wholesalePriceUSD?: T;
        costPriceUSD?: T;
        averageCostUSD?: T;
      };
  inventory?:
    | T
    | {
        stockQuantity?: T;
        minStock?: T;
        reorderPoint?: T;
      };
  active?: T;
  images?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  tenant?: T;
  reference?: T;
  product?: T;
  warehouse?: T;
  movementType?: T;
  quantity?: T;
  unitCostUSD?: T;
  totalValueUSD?: T;
  movementDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bill-of-materials_select".
 */
export interface BillOfMaterialsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  code?: T;
  finishedProduct?: T;
  yieldQuantity?: T;
  yieldUnit?: T;
  version?: T;
  status?: T;
  components?:
    | T
    | {
        rawMaterial?: T;
        quantity?: T;
        unit?: T;
        scrapPercentage?: T;
        unitCostSnapshot?: T;
        subtotalCostUSD?: T;
        id?: T;
      };
  costs?:
    | T
    | {
        laborCostUSD?: T;
        overheadCostUSD?: T;
        totalRawMaterialCostUSD?: T;
        totalBatchCostUSD?: T;
        unitProductionCostUSD?: T;
      };
  instructions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-orders_select".
 */
export interface ProductionOrdersSelect<T extends boolean = true> {
  tenant?: T;
  orderNumber?: T;
  bom?: T;
  finishedProduct?: T;
  sourceWarehouse?: T;
  targetWarehouse?: T;
  plannedQuantity?: T;
  producedQuantity?: T;
  status?: T;
  scheduledDate?: T;
  completedDate?: T;
  actualCosts?:
    | T
    | {
        actualTotalCostUSD?: T;
        actualUnitCostUSD?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  legalName?: T;
  rifTaxId?: T;
  phone?: T;
  email?: T;
  contactPerson?: T;
  creditConfig?:
    | T
    | {
        creditAllowed?: T;
        creditDays?: T;
        creditLimitUSD?: T;
      };
  currentDebtUSD?: T;
  currentDebtVES?: T;
  overdueDebtUSD?: T;
  lastPaymentDate?: T;
  paymentInstructions?: T;
  address?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-invoices_select".
 */
export interface PurchaseInvoicesSelect<T extends boolean = true> {
  tenant?: T;
  invoiceReference?: T;
  supplier?: T;
  warehouse?: T;
  paymentType?: T;
  status?: T;
  issueDate?: T;
  dueDate?: T;
  exchangeRateSnapshot?: T;
  totalUSD?: T;
  totalVES?: T;
  balanceUSD?: T;
  balanceVES?: T;
  items?:
    | T
    | {
        product?: T;
        sku?: T;
        description?: T;
        quantity?: T;
        unitCostUSD?: T;
        subtotalUSD?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-payments_select".
 */
export interface SupplierPaymentsSelect<T extends boolean = true> {
  tenant?: T;
  paymentNumber?: T;
  supplier?: T;
  paymentDate?: T;
  paymentMethod?: T;
  amountUSD?: T;
  exchangeRateApplied?: T;
  amountVES?: T;
  bankOrigin?: T;
  reference?: T;
  allocations?:
    | T
    | {
        purchaseInvoice?: T;
        allocatedAmountUSD?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-registers_select".
 */
export interface CashRegistersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  code?: T;
  warehouse?: T;
  currentStatus?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-closures_select".
 */
export interface CashClosuresSelect<T extends boolean = true> {
  tenant?: T;
  closureNumber?: T;
  cashRegister?: T;
  openedBy?: T;
  closedBy?: T;
  status?: T;
  openedAt?: T;
  closedAt?: T;
  openingFloat?:
    | T
    | {
        cashUSD?: T;
        cashVES?: T;
      };
  systemTotals?:
    | T
    | {
        cashUSD?: T;
        cashVES?: T;
        pagoMovilVES?: T;
        transferVES?: T;
        zelleUSD?: T;
        binanceUSD?: T;
        totalSalesUSD?: T;
      };
  declaredTotals?:
    | T
    | {
        cashUSD?: T;
        cashVES?: T;
        pagoMovilVES?: T;
        transferVES?: T;
        zelleUSD?: T;
        binanceUSD?: T;
      };
  differences?:
    | T
    | {
        diffCashUSD?: T;
        diffCashVES?: T;
        diffPagoMovilVES?: T;
        diffZelleUSD?: T;
        hasDiscrepancy?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}